### PR TITLE
fix (docs): Fixed a Typo

### PR DESCRIPTION
**Pull request by LautaroLobo12**
"you are be good to go!" --> "you are good to go!"

### CODE REVIEW

**Comment by LautaroLobo12** [comment]
That 'Semantic PR' ain't ✅. Should my commit messages be more descriptive?

**Comment by jsjoeio** [comment]
> That 'Semantic PR' ain't ✅. Should my commit messages be more descriptive?

Ah, no, don't worry about it!

**Comment by jsjoeio** [comment]
Thanks so much for fixing this! :D

**Comment by jsjoeio** [comment]
@all-contributors please add @LautaroLobo12 for docs

**Pull request merged**
